### Kreiranje indeksa knjige
PUT /knjige
{
  "settings": {
    "analysis": {
      "analyzer": {
        "hrvatski_analyzer": {
          "tokenizer": "standard",
          "filter": [
            "lowercase",
            "asciifolding"
          ]
        }
      }
    }
  },
  "mappings": {
    "properties": {
      "naslov": {
        "type": "text",
        "analyzer": "hrvatski_analyzer",
        "fields": {
          "keyword": {
            "type": "keyword"
          }
        }
      },
      "autor": { "type": "keyword" },
      "zanr": { "type": "keyword" },
      "opis": {
        "type": "text",
        "analyzer": "hrvatski_analyzer"
      },
      "godina": { "type": "integer" },
      "cijena": { "type": "double" },
      "dostupno": { "type": "boolean" }
    }
  }
}

### Bulk unos knjiga
POST /knjige/_bulk
{ "index": { "_id": "1" } }
{ "naslov": "Na Drini ćuprija", "autor": "Ivo Andrić", "zanr": "roman", "opis": "Povijesni roman o mostu, ljudima i vremenu.", "godina": 1945, "cijena": 18.50, "dostupno": true }
{ "index": { "_id": "2" } }
{ "naslov": "Derviš i smrt", "autor": "Meša Selimović", "zanr": "roman", "opis": "Filozofski roman o vlasti, pravdi i ljudskoj sudbini.", "godina": 1966, "cijena": 22.00, "dostupno": true }
{ "index": { "_id": "3" } }
{ "naslov": "Tvrđava", "autor": "Meša Selimović", "zanr": "roman", "opis": "Roman o čovjeku, društvu i borbi za smisao.", "godina": 1970, "cijena": 20.00, "dostupno": false }
{ "index": { "_id": "4" } }
{ "naslov": "Travnička hronika", "autor": "Ivo Andrić", "zanr": "povijesni roman", "opis": "Priča o diplomatskom i društvenom životu u Travniku.", "godina": 1942, "cijena": 19.90, "dostupno": true }
{ "index": { "_id": "5" } }
{ "naslov": "Zločin i kazna", "autor": "Fjodor Dostojevski", "zanr": "roman", "opis": "Psihološki roman o krivnji, savjesti i iskupljenju.", "godina": 1866, "cijena": 24.50, "dostupno": true }

### Provjera broja dokumenata
GET /knjige/_count

### Match – naslov (cuprija)
GET /knjige/_search
{
  "query": {
    "match": {
      "naslov": "cuprija"
    }
  }
}

### Match – opis (pravda vlast sudbina)
GET /knjige/_search
{
  "query": {
    "match": {
      "opis": "pravda vlast sudbina"
    }
  }
}

### Match – opis (roman)
GET /knjige/_search
{
  "query": {
    "match": {
      "opis": "roman"
    }
  }
}

### Match – opis (pravda sudbina)
GET /knjige/_search
{
  "query": {
    "match": {
      "opis": "pravda sudbina"
    }
  }
}

### Term – autor (Ivo Andrić)
GET /knjige/_search
{
  "query": {
    "term": {
      "autor": "Ivo Andrić"
    }
  }
}

### Range – godina >= 1950
GET /knjige/_search
{
  "query": {
    "range": {
      "godina": {
        "gte": 1950
      }
    }
  }
}

### Bool – dostupno, cijena ≤ 22, opis roman
GET /knjige/_search
{
  "query": {
    "bool": {
      "must": [
        {
          "match": {
            "opis": "roman"
          }
        }
      ],
      "filter": [
        {
          "term": {
            "dostupno": true
          }
        },
        {
          "range": {
            "cijena": {
              "lte": 22
            }
          }
        }
      ]
    }
  }
}

### Analyze – test 1
POST /knjige/_analyze
{
  "analyzer": "hrvatski_analyzer",
  "text": "Brzi smeđi most preko rijeke!"
}

### Analyze – test 2
POST /knjige/_analyze
{
  "analyzer": "hrvatski_analyzer",
  "text": "Na Drini ćuprija"
}

### Agregacija – broj knjiga po autoru
GET /knjige/_search
{
  "size": 0,
  "aggs": {
    "knjige_po_autoru": {
      "terms": {
        "field": "autor"
      }
    }
  }
}

### Agregacija – prosječna cijena po žanru
GET /knjige/_search
{
  "size": 0,
  "aggs": {
    "po_zanru": {
      "terms": {
        "field": "zanr"
      },
      "aggs": {
        "prosjecna_cijena": {
          "avg": {
            "field": "cijena"
          }
        }
      }
    }
  }
}

### Agregacija – najskuplja knjiga po žanru
GET /knjige/_search
{
  "size": 0,
  "aggs": {
    "po_zanru": {
      "terms": {
        "field": "zanr"
      },
      "aggs": {
        "najveca_cijena": {
          "max": {
            "field": "cijena"
          }
        }
      }
    }
  }
}

### Agregacija – dostupnost
GET /knjige/_search
{
  "size": 0,
  "aggs": {
    "dostupnost": {
      "terms": {
        "field": "dostupno"
      }
    }
  }
}

### Kreiranje indeksa filmovi
PUT /filmovi
{
  "settings": {
    "analysis": {
      "analyzer": {
        "hrvatski_analyzer": {
          "tokenizer": "standard",
          "filter": ["lowercase", "asciifolding"]
        }
      }
    }
  },
  "mappings": {
    "properties": {
      "naslov": { "type": "text" },
      "redatelj": { "type": "keyword" },
      "zanr": { "type": "keyword" },
      "opis": { "type": "text" },
      "godina": { "type": "integer" },
      "ocjena": { "type": "double" },
      "dostupno": { "type": "boolean" }
    }
  }
}

### Bulk unos filmova
POST /filmovi/_bulk
{ "index": { "_id": "1" } }
{ "naslov": "Deadpool", "redatelj": "Tim Miller", "zanr": "sci-fi", "opis": "Superherojski film o plaćeniku s moćima i crnim humorom", "godina": 2016, "ocjena": 8.0, "dostupno": true }
{ "index": { "_id": "2" } }
{ "naslov": "12 angry men", "redatelj": "Sidney Lumet", "zanr": "drama", "opis": "Drama o poroti koja odlučuje o krivnji optuženog", "godina": 1957, "ocjena": 9.0, "dostupno": true }
{ "index": { "_id": "3" } }
{ "naslov": "The Hangover", "redatelj": "Todd Phillips", "zanr": "komedija", "opis": "Nakon lude noći u Las Vegasu ekipa se pokušava sjetiti događanja", "godina": 2009, "ocjena": 7.7, "dostupno": true }
{ "index": { "_id": "4" } }
{ "naslov": "Južni vetar", "redatelj": "Milos Avramović", "zanr": "kriminalistički", "opis": "Film o Beogradskom podzemlju, kriminalu i opstanku", "godina": 2018, "ocjena": 8.1, "dostupno": true }
{ "index": { "_id": "5" } }
{ "naslov": "The Matrix", "redatelj": "Wachowski", "zanr": "sci-fi", "opis": "Borba protiv umjetne inteligencije", "godina": 1999, "ocjena": 8.7, "dostupno": true }
{ "index": { "_id": "6" } }
{ "naslov": "Home Alone", "redatelj": "Chris Columbus", "zanr": "komedija", "opis": "Dječak ostane sam u kući i bori se protiv lopova", "godina": 1990, "ocjena": 7.8, "dostupno": true }
{ "index": { "_id": "7" } }
{ "naslov": "Project X", "redatelj": "Nima Nourizadeh", "zanr": "komedija", "opis": "Tinejdžeri organizuju zabavu koja se izmiče kontroli", "godina": 2012, "ocjena": 6.7, "dostupno": true }
{ "index": { "_id": "8" } }
{ "naslov": "City of God", "redatelj": "Fernando Meirelles", "zanr": "kriminalistički", "opis": "Odrastanje u favelama Rio De Janeira", "godina": 2002, "ocjena": 8.6, "dostupno": true }

### Match – filmovi
GET /filmovi/_search
{
  "query": {
    "match": {
      "opis": "borba"
    }
  }
}

### Term – redatelj
GET /filmovi/_search
{
  "query": {
    "term": {
      "redatelj": "Milos Avramović"
    }
  }
}

### Range – ocjena > 8
GET /filmovi/_search
{
  "query": {
    "range": {
      "ocjena": {
        "gt": 8
      }
    }
  }
}

### Bool – filmovi
GET /filmovi/_search
{
  "query": {
    "bool": {
      "must": [
        {
          "match": {
            "opis": "film"
          }
        }
      ],
      "filter": [
        {
          "term": {
            "dostupno": true
          }
        },
        {
          "range": {
            "ocjena": {
              "gte": 7
            }
          }
        }
      ]
    }
  }
}

### Agregacija – filmovi
GET /filmovi/_search
{
  "size": 0,
  "aggs": {
    "po_zanru": {
      "terms": {
        "field": "zanr"
      },
      "aggs": {
        "prosjecna_ocjena": {
          "avg": {
            "field": "ocjena"
          }
        }
      }
    }
  }
}